name: Destroy AKS Deployment

on:
  workflow_dispatch:
    inputs:
      RESOURCE_GROUP:
        description: 'Azure Resource Group'
        required: true
      CLUSTER_NAME:
        description: 'AKS Cluster Name'
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete AKS Cluster
        run: |
          echo "Deleting AKS Cluster: ${{ github.event.inputs.CLUSTER_NAME }} in Resource Group: ${{ github.event.inputs.RESOURCE_GROUP }}"
          az aks delete \
            --name ${{ github.event.inputs.CLUSTER_NAME }} \
            --resource-group ${{ github.event.inputs.RESOURCE_GROUP }} \
            --yes \
            --no-wait
